import { Building2, Car, CircleDollarSign, HandCoins, HeartPulse, Home, Landmark, ShieldCheck, TrendingUp, WalletCards, type LucideIcon } from "lucide-react";

export type Service = { slug:string; title:string; short:string; description:string; eyebrow:string; rate:string; tenure:string; amount:string; icon:LucideIcon; image:"home"|"business"; benefits:string[]; documents:string[]; faqs:{q:string;a:string}[] };
const commonFaq=(title:string)=>[
 {q:`Who can apply for a ${title}?`,a:"Salaried and self-employed applicants may apply, subject to lender income, age, credit and document criteria."},
 {q:"How quickly can I get a decision?",a:"Timelines vary by lender and document readiness. FININSTA helps organise your file and coordinates updates with the selected lending partner."},
 {q:"Are the rates guaranteed?",a:"No. Rates and approval are decided by the lender after reviewing your profile, credit history, property or vehicle, and current policy."},
];
export const services:Service[]=[
 {slug:"home-loan",title:"Home Loan",short:"Competitive funding for your dream home.",description:"Compare suitable home loan options for purchase, resale or construction with expert support from application to disbursement.",eyebrow:"Home ownership",rate:"From 8.35% p.a.*",tenure:"Up to 30 years",amount:"Profile based",icon:Home,image:"home",benefits:["Options across leading lenders","Balance income and EMI comfortably","Support through legal and technical checks"],documents:["PAN and Aadhaar","Income proof and bank statements","Property papers","Employment or business proof"],faqs:commonFaq("home loan")},
 {slug:"plot-loan",title:"Plot Loan",short:"Finance for approved residential plots.",description:"Plan your land purchase with financing options for eligible residential plots across approved locations.",eyebrow:"Land finance",rate:"Competitive rates*",tenure:"Up to 15 years",amount:"Based on plot value",icon:Landmark,image:"home",benefits:["Guidance on plot eligibility","Multiple lender comparisons","Clear documentation support"],documents:["Identity and address proof","Income documents","Plot title and allotment papers","Approved layout documents"],faqs:commonFaq("plot loan")},
 {slug:"plot-construction-loan",title:"Plot + Construction Loan",short:"One plan for land and home construction.",description:"Combine plot purchase and phased home construction funding in a structured solution aligned to project progress.",eyebrow:"Build your home",rate:"Tailored pricing*",tenure:"Up to 30 years",amount:"Project based",icon:Building2,image:"home",benefits:["Single coordinated facility","Stage-wise disbursement guidance","Construction estimate support"],documents:["KYC and income proof","Plot papers","Approved building plan","Construction cost estimate"],faqs:commonFaq("plot and construction loan")},
 {slug:"balance-transfer",title:"Balance Transfer Loan",short:"Move your loan for better terms.",description:"Review your existing home loan and evaluate whether a balance transfer could improve rate, tenure or monthly cash flow.",eyebrow:"Optimise your EMI",rate:"Potential savings*",tenure:"Balance tenure",amount:"Outstanding balance",icon:TrendingUp,image:"home",benefits:["Existing loan health check","Savings comparison","End-to-end transfer support"],documents:["Existing sanction letter","Loan account statement","Income and KYC documents","Property papers"],faqs:commonFaq("balance transfer")},
 {slug:"top-up-loan",title:"Top-Up Loan",short:"Additional funds on an eligible home loan.",description:"Access additional finance over an existing eligible home loan for renovation, education, business or personal needs.",eyebrow:"Unlock extra value",rate:"Lender based*",tenure:"Flexible tenure",amount:"Eligibility based",icon:CircleDollarSign,image:"home",benefits:["Convenient additional funding","Potentially lower than unsecured credit","Simple consolidated repayment"],documents:["Current loan statement","Income proof","KYC documents","Purpose declaration"],faqs:commonFaq("top-up loan")},
 {slug:"loan-against-property",title:"Loan Against Property",short:"Unlock value from owned property.",description:"Raise funds against residential or commercial property for business expansion, education or other eligible needs.",eyebrow:"Property-backed finance",rate:"From competitive rates*",tenure:"Up to 20 years",amount:"Property based",icon:Landmark,image:"business",benefits:["Higher funding potential","Longer repayment options","Residential and commercial cases"],documents:["Property title chain","KYC and income proof","Bank statements","Business documents if applicable"],faqs:commonFaq("loan against property")},
 {slug:"od-dod-loan",title:"OD / DOD Loan",short:"Flexible credit against property.",description:"Manage working capital with overdraft-style property-backed funding where interest is generally charged on utilised funds.",eyebrow:"Flexible liquidity",rate:"On utilised amount*",tenure:"Renewable facility",amount:"Limit based",icon:WalletCards,image:"business",benefits:["Withdraw as needed","Interest on utilisation","Useful for business cash flow"],documents:["Property documents","Business financials","KYC documents","Banking history"],faqs:commonFaq("OD or DOD loan")},
 {slug:"personal-loan",title:"Personal Loan",short:"Quick unsecured finance for planned needs.",description:"Explore personal loan choices for weddings, travel, education, medical needs or debt consolidation with guided documentation.",eyebrow:"Fast personal finance",rate:"Profile based*",tenure:"Up to 7 years",amount:"Income based",icon:HandCoins,image:"business",benefits:["No collateral required","Digital document assistance","Flexible end-use"],documents:["PAN and Aadhaar","Salary slips","Bank statements","Employment proof"],faqs:commonFaq("personal loan")},
 {slug:"business-loan",title:"Business Loan",short:"Capital to grow your enterprise.",description:"Find working capital and growth finance for eligible businesses, professionals and entrepreneurs across India.",eyebrow:"Business growth",rate:"Custom pricing*",tenure:"Flexible",amount:"Cash-flow based",icon:Building2,image:"business",benefits:["Working capital support","Secured and unsecured options","Expert file preparation"],documents:["KYC and business proof","ITR and financial statements","GST returns where applicable","Bank statements"],faqs:commonFaq("business loan")},
 {slug:"car-loan",title:"Car Loan",short:"Drive home a new car with confidence.",description:"Compare new car finance options with practical down-payment, tenure and EMI guidance.",eyebrow:"New car finance",rate:"Competitive rates*",tenure:"Up to 7 years",amount:"Vehicle based",icon:Car,image:"home",benefits:["New vehicle financing","Flexible down-payment options","Dealer coordination support"],documents:["KYC documents","Income proof","Bank statements","Vehicle quotation"],faqs:commonFaq("car loan")},
 {slug:"used-car-loan",title:"Used Car Loan",short:"Smart finance for a pre-owned vehicle.",description:"Get support evaluating finance for eligible used cars, including valuation, lender matching and documentation.",eyebrow:"Pre-owned car finance",rate:"Vehicle based*",tenure:"Flexible",amount:"Valuation based",icon:Car,image:"business",benefits:["Eligible used-car funding","Valuation coordination","Transparent repayment view"],documents:["KYC and income proof","Vehicle RC and insurance","Valuation report","Seller documents"],faqs:commonFaq("used car loan")},
];
export const investmentService:Service={slug:"investment-insurance",title:"Investment & Insurance",short:"Protect today. Plan tomorrow.",description:"Build a balanced financial plan with suitable protection, health cover, long-term investments and disciplined savings guidance.",eyebrow:"Wealth & protection",rate:"Goal aligned",tenure:"Long-term plans",amount:"Personalised",icon:ShieldCheck,image:"business",benefits:["Term and health cover review","Goal-based investment planning","Clear risk and horizon discussion"],documents:["KYC documents","Income and tax details","Existing policy summary","Nominee details"],faqs:[{q:"Does FININSTA guarantee investment returns?",a:"No. Market-linked returns are not guaranteed. Recommendations should be assessed against your goals, time horizon and risk tolerance."},{q:"How much life cover should I consider?",a:"Cover needs depend on income, liabilities, dependants and long-term goals. A personal needs review is recommended."},{q:"Can I compare health insurance plans?",a:"Yes. We help you review cover, exclusions, waiting periods, network access and premium considerations."}]};
export const allServices=[...services,investmentService];
export const whatsappUrl=(message="I would like a free financial consultation with FININSTA.")=>`https://wa.me/917827881951?text=${encodeURIComponent(message)}`;
export const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n);
export const partners=["SBI","HDFC Bank","ICICI Bank","Axis Bank","Kotak Mahindra","PNB","Bank of Baroda","AU Small Finance","IDFC FIRST Bank"];
export const blogPosts=["Home Loan Guide for First-Time Buyers","How to Improve Your CIBIL Score","Fixed vs Floating Home Loan Rate","Home Loan Documents Checklist","Balance Transfer: When Does It Make Sense?","Loan Against Property Explained","How Personal Loan EMI Works","Business Loan Readiness Guide","New Car vs Used Car Finance","Understanding Loan Processing Fees","How Much Home Loan Can I Afford?","Co-applicant Benefits in Home Loans","Plot Loan vs Home Loan","Construction Loan Disbursement Guide","Term Insurance Buying Checklist","Health Insurance for Families","Goal-Based Investment Planning","Emergency Fund Essentials","Smart EMI Management Tips","Financial Planning for Self-Employed Professionals"];
