/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BanksRouteImport } from './routes/banks'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as InvestmentInsuranceRouteImport } from './routes/investment-insurance'
import { Route as NbfcRouteImport } from './routes/nbfc'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'
import { Route as LoansSlugRouteImport } from './routes/loans.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BanksRoute = BanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentInsuranceRoute = InvestmentInsuranceRouteImport.update({
  id: '/investment-insurance',
  path: '/investment-insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const NbfcRoute = NbfcRouteImport.update({
  id: '/nbfc',
  path: '/nbfc',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogsRoute,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogsRoute,
} as any)
const LoansSlugRoute = LoansSlugRouteImport.update({
  id: '/loans/$slug',
  path: '/loans/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/banks': typeof BanksRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/investment-insurance': typeof InvestmentInsuranceRoute
  '/nbfc': typeof NbfcRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/loans/$slug': typeof LoansSlugRoute
  '/blogs/': typeof BlogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/banks': typeof BanksRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/investment-insurance': typeof InvestmentInsuranceRoute
  '/nbfc': typeof NbfcRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/loans/$slug': typeof LoansSlugRoute
  '/blogs': typeof BlogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/banks': typeof BanksRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/investment-insurance': typeof InvestmentInsuranceRoute
  '/nbfc': typeof NbfcRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/loans/$slug': typeof LoansSlugRoute
  '/blogs/': typeof BlogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/banks'
    | '/blogs'
    | '/calculator'
    | '/contact'
    | '/investment-insurance'
    | '/nbfc'
    | '/privacy'
    | '/terms'
    | '/blogs/$slug'
    | '/loans/$slug'
    | '/blogs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/banks'
    | '/calculator'
    | '/contact'
    | '/investment-insurance'
    | '/nbfc'
    | '/privacy'
    | '/terms'
    | '/blogs/$slug'
    | '/loans/$slug'
    | '/blogs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/banks'
    | '/blogs'
    | '/calculator'
    | '/contact'
    | '/investment-insurance'
    | '/nbfc'
    | '/privacy'
    | '/terms'
    | '/blogs/$slug'
    | '/loans/$slug'
    | '/blogs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BanksRoute: typeof BanksRoute
  BlogsRoute: typeof BlogsRouteWithChildren
  CalculatorRoute: typeof CalculatorRoute
  ContactRoute: typeof ContactRoute
  InvestmentInsuranceRoute: typeof InvestmentInsuranceRoute
  NbfcRoute: typeof NbfcRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  LoansSlugRoute: typeof LoansSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banks': {
      id: '/banks'
      path: '/banks'
      fullPath: '/banks'
      preLoaderRoute: typeof BanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment-insurance': {
      id: '/investment-insurance'
      path: '/investment-insurance'
      fullPath: '/investment-insurance'
      preLoaderRoute: typeof InvestmentInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nbfc': {
      id: '/nbfc'
      path: '/nbfc'
      fullPath: '/nbfc'
      preLoaderRoute: typeof NbfcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/loans/$slug': {
      id: '/loans/$slug'
      path: '/loans/$slug'
      fullPath: '/loans/$slug'
      preLoaderRoute: typeof LoansSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogsRouteChildren {
  BlogsSlugRoute: typeof BlogsSlugRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsSlugRoute: BlogsSlugRoute,
  BlogsIndexRoute: BlogsIndexRoute,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BanksRoute: BanksRoute,
  BlogsRoute: BlogsRouteWithChildren,
  CalculatorRoute: CalculatorRoute,
  ContactRoute: ContactRoute,
  InvestmentInsuranceRoute: InvestmentInsuranceRoute,
  NbfcRoute: NbfcRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  LoansSlugRoute: LoansSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
